import { Inter, Great_Vibes } from 'next/font/google'; // Import fonts from Next.js
import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { twMerge } from 'tailwind-merge';

// Metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "700"], 
});


const greatVibes = Great_Vibes({
  subsets: ["latin"],
  variable: "--font-great-vibes",
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={twMerge(inter.variable, greatVibes.variable)}>
      <body className=" text-white antialiased font-sans">
        {/* Navbar at the top */}
        <Navbar />

        {/* Main content */}
        {children}

        {/* Footer at the bottom */}
        <Footer />
      </body>
    </html>
  );
}
